on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
         snyk auth <020360b3-074f-439e-8aee-ea831b40eacf>
           snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
